apiVersion: v1
kind: Service
metadata:
  name: wordscape
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"app-https":"HTTPS"}'
  labels:
    app: wordscape
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: app-https
  selector:
    app: wordscape
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordscape
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wordscape
    spec:
      containers:
      - name: wordscape-container
        image: gcr.io/translate-watson/wordscape:0.2
        ports:
        - containerPort: 8443
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordscape-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "wordscapesip"
spec:
  tls:
  - secretName: tls-secret
  backend:
    serviceName: wordscape
    servicePort: 443
